#!/usr/bin/env python3
"""
Regenerates the full PWA icon set from a source logo image.

Cross-platform replacement for the old sips-based generate_icons.sh.
Strips any white/near-white background to real transparency (instead of
baking a white square behind the logo), tightly & evenly crops the
artwork, and builds a maskable icon with a solid brand-colour backing
(not white) so it displays correctly under every OS mask shape.

Usage:
    pip install pillow
    python3 tools/generate_icons.py [path/to/Logo.png]

Requires the source logo to have the mark on a plain near-white
background (any resolution — bigger is better). If your source logo
already has real transparency, this still works: pixels that are
already transparent stay transparent, and near-white opaque pixels get
keyed out the same way.
"""
from __future__ import annotations

import sys
from pathlib import Path

from PIL import Image
import numpy as np

# Matches tassic.ui.theme.Navy / twa-manifest.json themeColor (#0F2B4C).
# Used as the maskable icon's edge-to-edge background so the launcher
# icon looks intentional under circular/squircle/rounded-square masks,
# instead of showing a white box.
NAVY = (15, 43, 76, 255)

OUT = Path("composeApp/src/wasmJsMain/resources")


def strip_white_bg(im: Image.Image, low: int = 232, high: int = 250) -> Image.Image:
    """Turn near-white background transparent with a soft feathered edge.

    Pixels darker than `low` stay fully opaque; pixels brighter than
    `high` become fully transparent; pixels in between are feathered
    linearly so edges stay smooth instead of jagged.
    """
    im = im.convert("RGBA")
    arr = np.array(im).astype(float)
    brightness = arr[:, :, :3].mean(axis=2)
    alpha = np.clip((high - brightness) / (high - low), 0, 1) * 255
    arr[:, :, 3] = np.minimum(alpha, arr[:, :, 3])
    return Image.fromarray(arr.astype("uint8"), "RGBA")


def autocrop(im: Image.Image, pad_ratio: float = 0.06) -> Image.Image:
    """Crop to the opaque content's bounding box, square it, pad evenly."""
    arr = np.array(im)
    ys, xs = np.where(arr[:, :, 3] > 10)
    if len(ys) == 0:
        return im
    y0, y1, x0, x1 = ys.min(), ys.max(), xs.min(), xs.max()
    cropped = im.crop((x0, y0, x1 + 1, y1 + 1))
    w, h = cropped.size
    side = max(w, h)
    pad = int(side * pad_ratio)
    canvas = Image.new("RGBA", (side + pad * 2, side + pad * 2), (0, 0, 0, 0))
    canvas.paste(cropped, ((side + pad * 2 - w) // 2, (side + pad * 2 - h) // 2), cropped)
    return canvas


def main() -> None:
    src_path = Path(sys.argv[1]) if len(sys.argv) > 1 else Path("Logo.png")
    if not src_path.is_file():
        sys.exit(f"Source logo not found: {src_path}")

    (OUT / "icons").mkdir(parents=True, exist_ok=True)

    squared = autocrop(strip_white_bg(Image.open(src_path)))

    squared.resize((480, 480), Image.LANCZOS).save(OUT / "logo.png")
    squared.resize((512, 512), Image.LANCZOS).save(OUT / "icons/icon-512.png")
    squared.resize((192, 192), Image.LANCZOS).save(OUT / "icons/icon-192.png")
    squared.resize((64, 64), Image.LANCZOS).save(OUT / "icons/favicon.png")

    # Maskable: solid brand-colour background, logo inset to the ~64-66%
    # safe zone so nothing gets clipped by circular/rounded-square masks.
    canvas = Image.new("RGBA", (512, 512), NAVY)
    safe_logo = squared.resize((330, 330), Image.LANCZOS)
    pos = ((512 - 330) // 2, (512 - 330) // 2)
    canvas.paste(safe_logo, pos, safe_logo)
    canvas.convert("RGB").save(OUT / "icons/maskable-512.png")

    print(f"PWA icons written to {OUT}/icons (192, 512, maskable-512, favicon).")
    print("Android launcher icons (mipmap-hdpi … xxxhdpi) are generated by Bubblewrap")
    print("at build time from icons/icon-512.png + icons/maskable-512.png.")


if __name__ == "__main__":
    main()
