#!/usr/bin/env bash
# Regenerates the full PWA icon set from the root logo.
# macOS: uses built-in sips. Linux: swap in ImageMagick `convert` equivalents.
set -euo pipefail

SRC="${1:-Logo.png}"
OUT="composeApp/src/wasmJsMain/resources"

[ -f "$SRC" ] || { echo "Source logo not found: $SRC"; exit 1; }

mkdir -p "$OUT/icons"

cp "$SRC" "$OUT/logo.png"
sips -z 192 192 "$SRC" --out "$OUT/icons/icon-192.png" >/dev/null
sips -z 512 512 "$SRC" --out "$OUT/icons/icon-512.png" >/dev/null
sips -z 64 64  "$SRC" --out "$OUT/icons/favicon.png"   >/dev/null

# Maskable variant: logo scaled into the 80% safe zone on a solid pad.
sips -z 410 410 "$SRC" --out /tmp/tassic-mask-410.png >/dev/null
sips --padToHeightWidth 512 512 --padColor FFFFFF /tmp/tassic-mask-410.png \
     --out "$OUT/icons/maskable-512.png" >/dev/null

echo "PWA icons written to $OUT/icons (192, 512, maskable-512, favicon)."
echo "Android launcher icons (mipmap-hdpi … xxxhdpi) are generated by Bubblewrap"
echo "at build time from icons/icon-512.png + icons/maskable-512.png."
